# Development docker-compose for DersLens - faster iteration
# version: '3.8'  # Docker Compose v2'de artık gerekli değil

services:
  # Backend API Service (Development)
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: derslens-backend-dev
    ports:
      - "8001:8000"
    volumes:
      - ./app:/app/app
      - backend_uploads:/app/uploads
    environment:
      - DEBUG=True
      - DATABASE_URL=sqlite:///./derslens.db
      - SECRET_KEY=derslens-dev-secret-key
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - derslens-network

  # Frontend Service (Development)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: derslens-frontend-dev
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_URL=http://localhost:8001
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - derslens-network

volumes:
  backend_uploads:

networks:
  derslens-network:
    driver: bridge
