# Development docker-compose for faster iteration
# version: '3.8'  # Docker Compose v2'de artık gerekli değil

services:
  # Backend API Service (Development)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: attention-pulse-backend-dev
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/app
      - backend_uploads:/app/uploads
    environment:
      - DEBUG=True
      - DATABASE_URL=sqlite:///./attention_pulse.db
      - SECRET_KEY=dev-secret-key
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - attention-pulse-network

  # Frontend Service (Development)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: attention-pulse-frontend-dev
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:8001
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - attention-pulse-network

volumes:
  backend_uploads:

networks:
  attention-pulse-network:
    driver: bridge
